spring:
  config:
    activate:
      on-profile: dev
#    import: aws-parameterstore:/config/glint/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://glint-db.cl4g4ogcerb5.ap-northeast-2.rds.amazonaws.com:3306/glint?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: glintserver
#  data:
#    redis:
#      host: ${cache.url}
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id:  ${oauth2.kakao.client-id}
#            client-secret: ${oauth2.kakao.client-secret}
  jms:
    pub-sub-domain: true

app:
  auth:
    tokenSecret: glintjwtsecretkey1234844saf23jsfoiau3oi4jesoidfjio
    refreshTokenExpirationMsec: 7776000000
    tokenExpirationMsec: 3600000
  oauth2:
    baseScheme: "http"

cloud:
  aws:
    credentials:
      accessKey: test
      secretKey: test
    s3:
      bucket: glint-image
