spring:
  application:
    name: glint
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f8036998a483e59f4b24f904a006c6e9
            client-secret: WBoQLLideGlijmNhNEKLkXZbYTHPh9F3
  data:
    redis:
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method

app:
  appScheme: "glint://"
  oauth2:
    authorizedRedirectUris:
      - https://api.glint.com/oauth2/callback/kakao
      - http://localhost:8080/oauth2/callback/kakao
      - glint://oauth
    baseScheme: "https"
  slack:
    webhook-url: https://hooks.slack.com/services/
    error-noti-token: TEST

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    root.level: info
