spring:
  config:
    activate:
      on-profile: dev
    import: aws-parameterstore:/config/glint/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  data:
    redis:
      host: ${cache.url}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:  ${oauth2.kakao.client-id}
            client-secret: ${oauth2.kakao.client-secret}
  jms:
    pub-sub-domain: true

app:
  auth:
    tokenSecret: glintjwtsecretkey1234844saf23jsfoiau3oi4jesoidfjio
    refreshTokenExpirationMsec: 7776000000
    tokenExpirationMsec: 3600000
  oauth2:
    basescheme: "https"

cloud:
  aws:
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}
    s3:
      bucket: glint-image
